## Automatic release process
# This workflow is a manually-triggered workflow, which automatically bumps the
# version and publishes the new crate version to crates.io. This uses an API
# token stored in the Github secret `CRATES_IO`.
name: Release crate
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new crate version to release, must be a non-existing version
        required: true
env:
  CRATES_IO: ${{ secrets.CRATES_IO }}
  VERSION: ${{ github.event.inputs.version }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release commit
        run: |
          sed -i "s/^version = .*$/version = \"${VERSION}\"/" Cargo.toml
          git config --global user.email 'noreply@github.com'
          git config --global user.name 'GitHub Actions Release Bot'
          git add Cargo.toml

          sed -i "s/^# unreleased$/# v${VERSION}/" CHANGELOG.md
          sed -i "1i # unreleased\n" CHANGELOG.md

          git commit -m "Release version \`${VERSION}\`" || :
          git push
      - name: Create tag
        run: git tag -a "${VERSION}" -m "v${VERSION}"
      - name: Push tag
        run: git push --tags
      - name: Publish to crates.io
        run: cargo publish --token "${CRATES_IO}"
